openapi: 3.0.0
info:
  title: Weather Backend API
  version: 1.0.0
paths:
  /lookup/{weather}:
    get:
      summary: Perform a weather lookup
      parameters:
        - name: weather
          in: path
          description: The weather to lookup
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  weather:
                    type: string
                  definition:
                    type: string
        '404':
          description: Weather not found
  /save:
    post:
      summary: Save a weather and its definition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                weather:
                  type: string
                definition:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
  /login:
    get:
      summary: Render the login page
      responses:
        '200':
          description: Successful response
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful authentication
        '401':
          description: Invalid credentials
  /:
    get:
      summary: Render the home page
      responses:
        '200':
          description: Successful response
